ROLE create query:
create table ROLE(ID INT AUTO_INCREMENT,NAME VARCHAR(20),DESCRIPTION VARCHAR(50),IS_ACTIVE BOOLEAN,CREATED_DATE DATETIME,MODIFIED_DATE DATETIME,PRIMARY KEY(ID));

EMPLOYEE create query:
create table EMPLOYEE(ID INT AUTO_INCREMENT,NAME VARCHAR(20),USERNAME VARCHAR(50),PASSWORD VARCHAR(50), EMAIL VARCHAR(50),REPORTING_PERSON_ID INT,IS_ACTIVE BOOLEAN,CREATED_DATE DATETIME,MODIFIED_DATE DATETIME,PRIMARY KEY(ID));

